USE [SmartHouse]
CREATE TABLE HID.Hidrometro
	(
	Codigo int NOT NULL IDENTITY (1, 1),
	Valor decimal(10, 2) NOT NULL,
	Data datetime NOT NULL,
	Excluido bit NOT NULL
	)  ON [PRIMARY];

ALTER TABLE HID.Hidrometro ADD CONSTRAINT
	PK_Hidrometro PRIMARY KEY CLUSTERED 
	(
	Codigo
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];

ALTER TABLE HID.Hidrometro SET (LOCK_ESCALATION = TABLE);