USE [SmartHouse]
ALTER TABLE HID.Valvula
	DROP CONSTRAINT PK_Valvula;

ALTER TABLE HID.Valvula ADD CONSTRAINT
	PK_Valvula PRIMARY KEY CLUSTERED 
	(
	Codigo
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];

ALTER TABLE HID.Valvula SET (LOCK_ESCALATION = TABLE);

CREATE TABLE HID.Vazamento
	(
	Codigo int NOT NULL IDENTITY (1, 1),
	CodigoValvula int NOT NULL,
	IndicadorVazamento bit NULL,
	Ativo bit NOT NULL,
	Data datetime NOT NULL,
	Excluido bit NOT NULL
	)  ON [PRIMARY];

ALTER TABLE HID.Vazamento ADD CONSTRAINT
	PK_Vazamento PRIMARY KEY CLUSTERED 
	(
	Codigo
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];

ALTER TABLE HID.Vazamento ADD CONSTRAINT
	FK_Vazamento_Valvula FOREIGN KEY
	(
	CodigoValvula
	) REFERENCES HID.Valvula
	(
	Codigo
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION;

ALTER TABLE HID.Vazamento SET (LOCK_ESCALATION = TABLE);