USE [SmartHouse]
CREATE TABLE ELE.TipoEnergia
	(
	Codigo int NOT NULL,
	Nome nvarchar(80) NOT NULL,
	Descricao nvarchar(MAX) NOT NULL,
	Ativo bit NOT NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY];

ALTER TABLE ELE.TipoEnergia ADD CONSTRAINT
	PK_TipoEnergia PRIMARY KEY CLUSTERED 
	(
	Codigo
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];

ALTER TABLE ELE.TipoEnergia SET (LOCK_ESCALATION = TABLE);