USE [SmartHouse]
ALTER TABLE SEG.Comodo
	DROP CONSTRAINT PK_Comodo;

ALTER TABLE SEG.Comodo ADD CONSTRAINT
	PK_Comodo PRIMARY KEY CLUSTERED 
	(
	Codigo
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];

ALTER TABLE SEG.Comodo SET (LOCK_ESCALATION = TABLE);

CREATE TABLE SEG.Presenca
	(
	Codigo int NOT NULL IDENTITY (1, 1),
	CodigoComodo int NOT NULL,
	IndicadorPresenca bit NULL,
	Ativo bit NOT NULL,
	Data datetime NOT NULL,
	Excluido bit NOT NULL
	)  ON [PRIMARY];

ALTER TABLE SEG.Presenca ADD CONSTRAINT
	PK_Presenca PRIMARY KEY CLUSTERED 
	(
	Codigo
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];

ALTER TABLE SEG.Presenca ADD CONSTRAINT
	FK_Presenca_Comodo FOREIGN KEY
	(
	CodigoComodo
	) REFERENCES SEG.Comodo
	(
	Codigo
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION;

ALTER TABLE SEG.Presenca SET (LOCK_ESCALATION = TABLE);