USE [SmartHouse]
ALTER TABLE ELE.TipoEnergia SET (LOCK_ESCALATION = TABLE);

CREATE TABLE ELE.Energia
	(
	Codigo int NOT NULL IDENTITY (1, 1),
	CodigoTipoEnergia int NOT NULL,
	Tensao int NOT NULL,
	Corrent int NOT NULL,
	Data datetime NOT NULL,
	Excluido bit NOT NULL
	)  ON [PRIMARY];

ALTER TABLE ELE.Energia ADD CONSTRAINT
	PK_Energia PRIMARY KEY CLUSTERED 
	(
	Codigo
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];

ALTER TABLE ELE.Energia ADD CONSTRAINT
	FK_Energia_TipoEnergia FOREIGN KEY
	(
	CodigoTipoEnergia
	) REFERENCES ELE.TipoEnergia
	(
	Codigo
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION;

ALTER TABLE ELE.Energia SET (LOCK_ESCALATION = TABLE);